### ISSUE TITLE
Default landig page slug

### ISSUE THREAD

**Issue by danaskallman** [meitar/multisite-directory#10]
I'm testing this on Cosecha, see her https://cosecha.dev.glocal.coop/blog/network_directory/ and realize that the slug is network_directory. Could it be changed to - so it's network-directory? That will match how other categories or page slugs are displayed and seems more consistent.

**Comment by danaskallman** [comment]
Thanks!

Right now I am using WP plugin repo to get plugin, is it better to use this repo?

**Comment by fabacab** [comment]
If you want to test with the latest changes, use this repo, but leave ANP's Composer pointing at the WP plugin directory since that'll stay stable.
