### ISSUE TITLE
Sites Appear When Deleted, Archived or Spam

### ISSUE THREAD

**Issue by misfist** [meitar/multisite-directory#12]
Currently, if a site is deleted, archived or spam, the site still appears in the directory.

It seems like if the site is deactivated or archived, it shouldn't appear in the directory listing (front-end). I can get the site status using [`get_blog_status`](https://codex.wordpress.org/WPMU_Functions/get_blog_status), but it might be nice if that happened auto-magically. :)

![sites network admin activist network wordpress 2016-04-13 21-10-39](https://cloud.githubusercontent.com/assets/709248/14515008/d63b14fa-01c3-11e6-8f03-7b77b6bc66cc.png)

**Comment by fabacab** [comment]
Thaaat is a good point. :) Will do.
