### ISSUE TITLE
Option to exclude or include site

### ISSUE THREAD

**Issue by danaskallman** [meitar/multisite-directory#17]
Is there a way to add the option to for example exclude site 1 or the parent site of the multsite. This is the site where the directory would live, so I imagine that site itself does not need to be listed.

**Comment by fabacab** [comment]
Since these are just pages, will trashing or unpublishing that one page work?

**Comment by danaskallman** [comment]
Hmmm, right, that makes sense. Closing as that works and can revisit if more detailed needs arise.
