### ISSUE TITLE
Upcoming Multisite Changes

### ISSUE THREAD

**Issue by misfist** [meitar/multisite-directory#18]
In case you haven't been following multi-site development, I wanted to draw your attention to some interesting changes coming up:

`WP_Site_Query` - With `WP_Site` is being merged in [#32450](https://core.trac.wordpress.org/ticket/32450) and there will be a new class for querying for sites. 
https://core.trac.wordpress.org/ticket/35791

Deprecate `wp_get_sites()` - Now that `get_sites()` has been introduced (https://core.trac.wordpress.org/changeset/37616) as part of `WP_Site_Query`, `wp_get_sites()` will be deprecated.

Network Admin Should Have its Own Settings API - This feature request might come to be.
https://core.trac.wordpress.org/ticket/36994

https://core.trac.wordpress.org/ticket/15691

**Comment by fabacab** [comment]
I wasn't aware of these upcoming additions, thanks.
