### ISSUE TITLE
Shortcode Filtering by category won't work

### ISSUE THREAD

**Issue by edemir206** [meitar/multisite-directory#25]
Hi,

My Problem is when I place the shortcode: [site-directory display="list" query_args='{"category": "templates"}' ] it's shows all the categories and all sites. It seems it's not apllying the filter. What am I missing ?

 Btw thanks for this great plugin,

**Comment by fabacab** [comment]
Pretty sure you want `cat`, not `category`. Please refer to [the relevant WordPress documentation](https://developer.wordpress.org/reference/classes/wp_query/#category-parameters). Also, consider using [this plugin's support forum](https://wordpress.org/support/plugin/multisite-directory) to ask for tech support, not this issue tracker. This is for development, bug reports, and so forth.
