### ISSUE TITLE
Site Logo Display

### ISSUE THREAD

**Issue by misfist** [meitar/multisite-directory#4]
Site logo support will soon be added to core (was a JetPack feature). I would be useful to be able to display the site logo in the site directory. This can be done on the theme-level, of course, but I wanted to mention it in case anyone thought it would be useful to incorporate into the plugin. For instance, maybe the post featured image could become the site-logo.

https://make.wordpress.org/core/2016/02/24/theme-logo-support/

**Comment by fabacab** [comment]
+1, good addition. I'm not yet clear how the site logo image data itself is stored but if it's available from code we can probably just use it as a default and use the directory entry's featured image as a directory-specific "site logo" iff an admin applies one. That way the Site Admin of a specific site still has control over their site logo for the directory but can be overridden by the Network's Super Admin.

**Comment by misfist** [comment]
In version 4.5, it looks like this will be called via `custom-logo` rather than `site-logo`.

The following functions will be available:

`get_custom_logo( $blog_id = 0 )`
Returns markup for a custom logo.

`the_custom_logo( $blog_id = 0 )`
Displays markup for a custom logo.

`has_custom_logo( $blog_id = 0 )`
Returns a boolean true/false, whether a custom logo is set or not.

https://make.wordpress.org/core/2016/03/10/custom-logo/

**Comment by misfist** [comment]
Actually, I see now that you're already using `the_custom_logo()`. Great.
